[PyTorch] Fix lower PR version for strip (#1895)
### Changes

- As in the title

### Reason for changes

- Bug with PyTorch 1.9.9:
`11:51:05  observer = torch.ao.quantization.observer.MinMaxObserver`
`11:51:05  AttributeError: module 'torch' has no attribute 'ao'`
- `torch.ao.quantization.observer.MinMaxObserver` was introduced only in
the 1.10 version