Add timeout for load extension (#1708)
### Changes

Add timeout for for load extensions. 
If loading hangs raise exception with message:
```
nncf.torch.extensions.ExtensionLoaderTimeoutException: The extension load function failed to execute within 1 seconds.
This may be due to leftover lock files from the PyTorch C++ extension build process.
If this is the case, running the following command should help:
    rm -rf ~/.cache/torch_extensions/binarized_functions_cuda/1.13.1+cu117
For a machine with poor performance, you may try increasing the time limit by setting the environment variable:
    NNCF_EXTENSION_LOAD_TIMEOUT=180
Or disable timeout by set:
    NNCF_EXTENSION_LOAD_TIMEOUT=0
For more information, see FAQ entry at: https://github.com/openvinotoolkit/nncf/blob/develop/docs/FAQ.md#importing-anything-from-nncftorch-hangs
```

### Reason for changes

Loading extensions may hang if lock file exists.

### Related tickets

107820

### Tests
```
torch.binarization.test_timeout_extension_loader[cpu]
torch.binarization.test_timeout_extension_loader[cuda]
torch.quantization.extensions.test_timeout_extension_loader[cpu]
torch.quantization.extensions.test_timeout_extension_loader[cuda]
```

TODO: 
- [x] collect statistics of times to build extension
- [x] Mac OS, win?