Added raising an exception when empty calibration dataset is provided (#2230)
### Changes

Added raising an exception when an empty calibration dataset is
provided.

Now if empty calibration dataset is passed to `nncf.quantize()` the
following exception will be thrown:
```
Calibration dataset must not be empty. Please provide calibration dataset with at least one sample.
```

Also added a check for non-positive `subset_size` provided to
`nncf.quantize()`. Otherwise, it would error with the same statistics
not collected error.

### Reason for changes

Without an explicit exception it will error out later with a message
like:
```
File "/home/nsavel/workspace/openvino_notebooks/nncf/nncf/quantization/algorithms/min_max/algorithm.py", line 673, in apply
    raise RuntimeError(f"Statistics were not collected for the node {target_node_name}")
RuntimeError: Statistics were not collected for the node /model.2/m.2/Add
```

This is confusing and does not clearly reflect what is actually wrong.
There have been some reports, e.g. from OTX side, when an error like
this was encountered due to empty dataset. But at first it wasn't clear
what's the issue actually is, and a bug in NNCF was suspected.

I personally also encounter this sometimes during experimenting and this
triggers me to look for issues in NNCF, however it was just an empty
calibration dataset provided by mistake.

### Tests

Added a test for empty dataset to `common/test_statistics_aggregator.py`
Added a test for non-positive `subset_size` to
`tests/openvino/native/quantization/test_quantize_api.py` (openvino
only).

---------

Co-authored-by: Alexander Suslov <alexander.suslov@intel.com>