Fix converting FQ to native torch given  `narrow_range`  (#1797)
### Changes

- When converting FQ to native torch levels, increase levels if
`narrow_range` is `True` for `SymmetricQuantizaer`.
- Clamp weights on strip model, if `narrow_range` is `True`.
- Add tests converting to ONNX for 8bit.

### Reason for changes

Error on export to ONNX
```
SymbolicValueError: For (quant_min, quant_max), ONNX allows only (0, 127), (0, 255) and (-128, 127). Got (-127, 127)
```

### Related tickets

110498