[PT] torch 2.2.1 (#2514)
### Changes

- Update torch to 2.2.1 
- Fix in torch version in examples.

Updates in relative tests:

1. `test_onnx_export.test_preserves_onnx_node_name_format[quantization]`
```
    assert 'Identity_0' in {'//nncf_model_input_0|OUTPUT/Constant', '//nncf_model_input_0|OUTPUT/Constant_1', '//nncf_model_input_0|OUTPUT/FakeQu...LinearTestModel/AdaptiveAvgPool2d[avg_pool]/adaptive_avg_pool2d_0|OUTPUT/FakeQuantize', '/bn1/BatchNormalization', ...}
     +  where 'Identity_0' = input: "bn2.weight"\noutput: "bn2.running_var"\nname: "Identity_0"\nop_type: "Identity"\n.name
```
Reason: Identity node have differ index after quantization.

2. `test_pytorch_patch.test_jit_if_tracing_script_source`
```
assert torch_source == nncf_source_corrected
```
Reason: Added typehint annotation for `torch.jit._script_if_tracing`
function.

3. `pruning.experimental.test_nodes_grouping.test_groups[Wave2Vec 2.0]`
```
RuntimeError: cannot create std::vector larger than max_size()
```
Fails without `nncf`, update config fixed the problem.