Typo was fixed (#1638)
### Changes

The typo was fixed in the `get_weight_value()` method.

### Reason for changes

TypeError: get_input_edges() missing 1 required positional argument:
'node'

### Related tickets

N/A

### Tests

tests/openvino/native/test_node_utils.py