Updated requirements of the ptq tensorflow mobilenet_v2 example (#2093)
### Changes

tensorflow>=2.7.0,<2.12 => tensorflow~=2.12.0

### Reason for changes

Installation errors:
ERROR: google-auth 2.22.0 has requirement urllib3<2.0, but you'll have
urllib3 2.0.4 which is incompatible.
ERROR: tensorflow-metadata 1.14.0 has requirement
protobuf<4.21,>=3.20.3, but you'll have protobuf 3.19.6 which is
incompatible.
ERROR: tensorflow-datasets 4.9.2 has requirement protobuf>=3.20, but
you'll have protobuf 3.19.6 which is incompatible.

### Related tickets

N/A

### Tests

example tests (build 73)