[test_examples] Install WWB version compatible with nightly openvino-genai (#3339)
### Changes

`whowhatbench` tool depends on `openvino-genai` module, but it takes it
from PyPI by default, so it depends on released OpenVINO version, so it
install it and we're getting this in validation cycles:
```
ImportError: libopenvino.so.2500: cannot open shared object file: No such file or directory
```

This PR hacks `test_examples.py` (`llm_tune_params` test to be exact) to
install nightly versions of `openvino-genai` and `whowhatbench`