[tests] Get rid of pkg_resources that is deprecated (#4188)
### Changes

Need to get rid of deprecated `import pkg_resources`

### Reason for changes

- since newer setuptools (e.g. 84) we are getting following error in
validation:
```
Traceback (most recent call last):
  File "/home/jenkins/agent/workspace/DL-Benchmark/precommit_pnp/PR-7296/W_calibr_public-default_small/nncf/tests/openvino/tools/calibrate.py", line 31, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

It was a warning for a long time now:
```
[2026-09-04T13:16:38.133Z] ForkPoolWorker-17: /home/jenkins/agent/workspace/DL-Benchmark/precommit_pnp/master_942046a7/W_calibr_public-default_small/nncf/tests/openvino/tools/calibrate.py:31: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
```