[ci] Fix install tests (#4028)
### Changes

Use `importlib.import_module` to check module instead of removed method
since python3.12

### Reason for changes


https://github.com/openvinotoolkit/nncf/actions/runs/24110960527/job/70345151170

```
    loader.find_module(module_name).load_module(module_name)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'FileFinder' object has no attribute 'find_module'
```

### Related tickets

https://github.com/openvinotoolkit/nncf/pull/3786

### Tests

https://github.com/openvinotoolkit/nncf/actions/runs/24124889586