Update main.py due to the issues 2669
AttributeError: 'list' object has no attribute 'keys'
change the L149 of the main.py to
validator.stats = dict(tp_m=[], tp=[], conf=[], pred_cls=[], target_cls=[])