Use full name of dataset  (#3861)
### Changes

Use full name of dataset `Salesforce/wikitext2` instead of `wikitext`
Bump dataset to 4.5.0
Set xfail for `test_nncf_profiling_notebook` - CVS-180038

### Reason for changes 

```
FAILED tests/openvino/native/quantization/test_weights_compression_statistics_caching.py::test_weight_compression_statistics_caching - 
huggingface_hub.errors.HfHubHTTPError: 404 Client Error: Not Found for url: 
https://huggingface.co/api/datasets/wikitext/revision/b08601e04326c79dfdd32d625aee71d232d685c3 (Request ID: Root=1-69784b6c-21934181316a6063784b169f;0cab8945-4cc5-4f90-bf49-d4c08d656488)
```

### Tests

https://github.com/openvinotoolkit/nncf/actions/runs/21396138596
https://github.com/openvinotoolkit/nncf/actions/runs/21396569371