Set weight without overriding convert node (#3337)
### Changes

Assign the weight to the constant operation, rather than the first
operation following the matrix multiplication.

### Reason for changes

In the past, the weights were assigned to the first operation after the
Matmul, and this approach functioned properly when the weights were in
float32 format. However, with the introduction of the ability to use
float16/bfloat16 weights in AWQ, as described in the pull request #3330,
the set_weights function no longer operates correctly. The first
operation in the process is a `Convert`, which is replaced by a
constant, and this causes an error:

```
RuntimeError: Check 'element::Type::merge(result_et, get_input_element_type(0), get_input_element_type(1))' failed at src\core\src\op\matmul.cpp:113:
While validating node 'opset1::MatMul MatMul_1657124 (opset1::Multiply __module.model.layers.0.post_attention_layernorm/aten::mul/Multiply_1[0]:f32[?,?,4096], opset1::Reshape Reshape_511646[0]:f16[14336,4096]) -&gt; (dynamic[...])' with friendly_name 'MatMul_1657124':
```


![image](https://github.com/user-attachments/assets/2aa4b1a0-bdf0-42fa-ab55-aba1d404d83a)

### Related tickets

163980
 should also fix tests in Optimum: 

### Tests

- [x] test_set_weight
- [x]
`tests/openvino/test_quantization.py::OVWeightCompressionTest::test_ovmodel_4bit_auto_compression_with_config_07`
and
`tests/openvino/test_quantization.py::OVWeightCompressionTest::test_ovmodel_4bit_auto_compression_with_config_08`
in Optimum have started to work, but failed before:
https://github.com/huggingface/optimum-intel/actions/runs/13713350054/job/38353813210