Removed specialized export for NAS models. (#1419)
### Changes

Removed specialized export for NAS models and rewrote assertions in nas tests.

When assertion happens on calculation of number of nodes it tries to output the whole expression (onnx proto), and sometimes it causes pytest to freeze:
```
E       assert 65 == 66
E        +  where 65 = len([input: "onnx::Conv_229"\n  output:...74,-\264\272\315\363O\273\373\302h<,\.....
```
Introduced a temporary variable for number of nodes to avoid the hang.

### Reason for changes

The custom export for NAS models was introduced as a temporary solution for a sporadic hang in NAS tests. Hang was root caused, and the reason is not export in eval mode, but issue with onnx expression on assertion.

### Related tickets

n/a

### Tests

pre-commit scope