Fix TypeError: revert_operations_to_floating_point_precision() missing 2 required positional arguments (#2484)
### Changes

Fix typo

### Reason for changes

TypeError: revert_operations_to_floating_point_precision() missing 2
required positional arguments: 'is_node_with_weight_fn' and
'get_weight_tensor_port_ids_fn'

### Related tickets

N/A

### Tests

Current scope