Add `pylintfileheader` plugin to check copyrights (#1833)
### Changes

Add `pylintfileheader` plugin to check copyrights.

Add https://github.com/HaaLeo/pylint-file-header plugin for pylint in
requirements.
Pattern of copyrights saved in '.file-header'
```
# Copyright \(c\) (\d{4}|\d{4}-\d{4}) Intel Corporation
# Licensed under the Apache License, Version 2.0 \(the "License"\);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
```

Update pylint config
```
load-plugins=pylintfileheader
file-header-path=.file-header
file-header-ignore-empty-files=yes
```
file-header-ignore-empty-files - skip empty file, like some __init__.py.

On fail check will raise error C5001:
```
************* Module nncf.quantization.algorithms.fast_bias_correction.backend
nncf/quantization/algorithms/fast_bias_correction/backend.py:1:0: C5001: File header must match regex "# Copyright \(c\) (\d{4}|\d{4}-\d{4}) Intel Corporation
# Licensed under the Apache License, Version 2.0 \(the "License"\);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
" (invalid-file-header)

-------------------------------------------------------------------
Your code has been rated at 9.68/10 (previous run: 10.00/10, -0.32)
```

It's bad, that full header shows in pylint log but it can not be
changed.