Bump transformers version (#3272)
### Changes

- Bumped `transformers` version to `>=4.48.0`
- Bumped `optimum-intel` version to `>=1.22.0` (as it requires
`transformers`)
- Bumped `optimum` version to `>=1.24.0` (as it requires `transformers`)
- Updated statistics caching test with `position_ids` to fix:

    >Exception from src/plugins/intel_cpu/src/node.cpp:769:
[CPU] Concat node with name
'__module.model.model.decoder.layers.0.self_attn/aten::cat/Concat' Check
'TRShape::merge_into(output_shape, in_copy)' failed at
src/core/shape_inference/include/concat_shape_inference.hpp:43:
While validating node 'opset1::Concat
__module.model.model.decoder.layers.0.self_attn/aten::cat/Concat
(opset1::Parameter Parameter_753753[0]:f32[?,4,?,4], opset1::Transpose
__module.model.model.decoder.layers.0.self_attn/aten::transpose/Transpose_1[0]:f32[?,4,?,4])
-> (f32[?,4,?,4])' with friendly_name
'__module.model.model.decoder.layers.0.self_attn/aten::cat/Concat':
Shape inference input shapes {{1,4,0,4},{0,4,0,4}}
Argument shapes are inconsistent; they must have the same rank, and must
have equal dimension everywhere except on the concatenation axis (axis
2).
- Bumped `accelerate` version to `>=1.1.0` to fix:

> NotImplementedError: data_seed requires Accelerate version
`accelerate` >= 1.1.0. This is not supported and we recommend you to
update your version.
- Added `num_items_in_batch` to `compute_loss` to fix:

> TypeError: CompressionTrainer.compute_loss() got an unexpected keyword
argument 'num_items_in_batch'
- Bumped `_ONNX_DEFAULT_OPSET` from 13 to 14 to fix:

> torch.onnx.errors.UnsupportedOperatorError: Exporting the operator
'aten::scaled_dot_product_attention' to ONNX opset version 13 is not
supported. Support for this operator was added in version 14, try
exporting with this version.

- Updated sparsity/pruning/nas references for tests.
### Reason for changes

- Security issues with `transformers<4.48`

### Related tickets

- N/A

### Tests

- install -
https://github.com/openvinotoolkit/nncf/actions/runs/13393410660 -
passed
- weight compression -
https://github.com/openvinotoolkit/nncf/actions/runs/13393412141 -
passed
- examples -
https://github.com/openvinotoolkit/nncf/actions/runs/13393412919 -
passed
- PTQ - manual/job/post_training_quantization/622/ - passed
- PTWC - manual/job/post_training_weight_compression/327/ - passed

---------

Co-authored-by: Nikolay Lyalyushkin <nikolay.lyalyushkin@intel.com>